import { ConflictException, Injectable, NotFoundException } from '@nestjs/common'; import { InjectRepository } from '@nestjs/typeorm'; import { Repository } from 'typeorm'; import * as bcrypt from 'bcrypt'; import { Student } from '../entities/student.entity'; import { User,UserRole } from '../entities/user.entity'; import { Grade } from '../entities/grade.entity'; import { StudentSubject } from '../entities/student-subject.entity'; import { CreateStudentDto,UpdateStudentDto } from './students.dto';
@Injectable() export class StudentsService {
 constructor(@InjectRepository(Student) private studentRepo:Repository<Student>,@InjectRepository(User) private userRepo:Repository<User>,@InjectRepository(Grade) private gradeRepo:Repository<Grade>,@InjectRepository(StudentSubject) private enrollmentRepo:Repository<StudentSubject>){ }
 async findAll(){return this.studentRepo.find({relations:{user:true,grade:true}});}
 async findOne(id:number){const x=await this.studentRepo.findOne({where:{id},relations:{user:true,grade:true}});if(!x)throw new NotFoundException('Student not found');return x;}
 async create(dto:CreateStudentDto){const grade=await this.gradeRepo.findOne({where:{id:dto.gradeId}});if(!grade)throw new NotFoundException('Grade not found');if(await this.userRepo.findOne({where:{email:dto.email}}))throw new ConflictException('Email is already registered');const user=await this.userRepo.save(this.userRepo.create({fullName:dto.fullName,email:dto.email,password:await bcrypt.hash(dto.password,10),phone:dto.phone,role:UserRole.STUDENT}));return this.studentRepo.save(this.studentRepo.create({user,grade,academicYear:dto.academicYear}));}
 async update(id:number,dto:UpdateStudentDto){const s=await this.findOne(id);if(dto.gradeId){const g=await this.gradeRepo.findOne({where:{id:dto.gradeId}});if(!g)throw new NotFoundException('Grade not found');s.grade=g;}Object.assign(s.user,{fullName:dto.fullName??s.user.fullName,email:dto.email??s.user.email,phone:dto.phone??s.user.phone});if(dto.password)s.user.password=await bcrypt.hash(dto.password,10);if(dto.academicYear)s.academicYear=dto.academicYear;await this.userRepo.save(s.user);await this.studentRepo.save(s);return this.findOne(id);}
 async remove(id:number){const s=await this.findOne(id);await this.studentRepo.remove(s);await this.userRepo.delete(s.user.id);return{message:'Student deleted successfully'};}
 async enrolled(id:number){await this.findOne(id);return this.enrollmentRepo.find({where:{student:{id}},relations:{subject:{grade:true,teacher:{user:true}}}});}
}
