import { ConflictException, Injectable, NotFoundException } from '@nestjs/common'; import { InjectRepository } from '@nestjs/typeorm'; import { Repository } from 'typeorm'; import { Subject } from '../entities/subject.entity'; import { Grade } from '../entities/grade.entity'; import { Teacher } from '../entities/teacher.entity'; import { StudentSubject } from '../entities/student-subject.entity';
@Injectable() export class SubjectsService{constructor(@InjectRepository(Subject)private repo:Repository<Subject>,@InjectRepository(Grade)private gradeRepo:Repository<Grade>,@InjectRepository(Teacher)private teacherRepo:Repository<Teacher>,@InjectRepository(StudentSubject)private enrollmentRepo:Repository<StudentSubject>){}
 async findAll(gradeId?:number){return this.repo.find({where:gradeId?{grade:{id:gradeId}}:{},relations:{grade:true,teacher:{user:true}}});}
 async findOne(id:number){const x=await this.repo.findOne({where:{id},relations:{grade:true,teacher:{user:true}}});if(!x)throw new NotFoundException('Subject not found');return x;}
 async create(dto:any){const grade=await this.gradeRepo.findOne({where:{id:dto.gradeId}});if(!grade)throw new NotFoundException('Grade not found');const teacher=await this.teacherRepo.findOne({where:{id:dto.teacherId}});if(!teacher)throw new NotFoundException('Teacher not found');return this.repo.save(this.repo.create({name:dto.name,description:dto.description,grade,teacher}));}
 async update(id:number,dto:any){const s=await this.findOne(id);if(dto.gradeId){const g=await this.gradeRepo.findOne({where:{id:dto.gradeId}});if(!g)throw new NotFoundException('Grade not found');s.grade=g;}if(dto.teacherId){const t=await this.teacherRepo.findOne({where:{id:dto.teacherId}});if(!t)throw new NotFoundException('Teacher not found');s.teacher=t;}if(dto.name!==undefined)s.name=dto.name;if(dto.description!==undefined)s.description=dto.description;return this.repo.save(s);}
 async remove(id:number){const s=await this.findOne(id);await this.repo.remove(s);return{message:'Subject deleted successfully'};}
 async enrolledStudents(id:number){await this.findOne(id);return this.enrollmentRepo.find({where:{subject:{id}},relations:{student:{user:true,grade:true}}});}
}
